version: '3.8'
services:
  # redis:
  #   image: redis:7
  #   ports: ["6379:6379"]
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: jobqueue
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: pass
  #   ports: ["5432:5432"]
  jobqueue:
    build: .
    env_file: .env
    # depends_on: [redis, postgres]
    ports: ["8080:8080"]
  prometheus:
    image: prom/prometheus
    volumes:
      - ./internal/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports: ["9090:9090"]
  grafana:
    image: grafana/grafana
    volumes:
      - ./internal/monitoring/grafana.json:/var/lib/grafana/dashboards/jobqueue.json
      - ./internal/monitoring/provisioning/:/etc/grafana/provisioning/
    environment:
      GF_DASHBOARDS_JSON_ENABLED: "true"
      GF_DASHBOARDS_JSON_PATH: "/var/lib/grafana/dashboards"
    depends_on: [prometheus]
    ports: ["3000:3000"]
